server:
  port: 8080
  servlet:
    context-path: /bookingtravel
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/bookingtravel"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "h0gQLmAkxCIHeXGVZ6nLd6oOUmoSWwqb1TPPFEB12xziloPik6X2sOe1Lqj4mSkf"
  valid-duration: 1500 #second
  refreshable-duration: 12000 #second